# Generated by Django 3.2.23 on 2023-12-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='workers_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workername', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('landmark', models.CharField(default=1, max_length=1000)),
                ('place', models.CharField(default=1, max_length=100)),
                ('postcode', models.CharField(default=1, max_length=100)),
                ('latitude', models.CharField(default=1, max_length=100)),
                ('longitude', models.CharField(default=1, max_length=100)),
                ('aadhar', models.CharField(default=1, max_length=100)),
                ('photo', models.CharField(max_length=1000)),
                ('LOGIN_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=1000)),
                ('LOGIN_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='secret_code_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('USER_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.user_table')),
                ('WORKER_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.workers_table')),
            ],
        ),
        migrations.CreateModel(
            name='request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('latitude', models.CharField(default=1, max_length=1000)),
                ('longitude', models.CharField(default=1, max_length=1000)),
                ('status', models.CharField(default=1, max_length=100)),
                ('USER_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.user_table')),
                ('WORKER_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.workers_table')),
            ],
        ),
        migrations.CreateModel(
            name='rating_review_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.user_table')),
                ('WORKER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.workers_table')),
            ],
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('USER_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.user_table')),
                ('WORKER_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.workers_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=1000)),
                ('USER_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='credit_point_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('coins', models.CharField(max_length=100)),
                ('PAYMENT_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.payment_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaints_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=1000)),
                ('ctype', models.CharField(max_length=20)),
                ('reply', models.CharField(max_length=200)),
                ('rdate', models.CharField(max_length=20)),
                ('LOGIN_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.login_table')),
            ],
        ),
    ]
