# Generated by Django 3.2.23 on 2024-01-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DriveInnapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('USER_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.user_table')),
                ('WORKER_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.workers_table')),
            ],
        ),
    ]
