# Generated by Django 3.2.21 on 2024-02-18 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DriveInnapp', '0003_auto_20240216_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_table',
            name='time',
        ),
    ]
