# Generated by Django 3.2.21 on 2024-02-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveInnapp', '0005_alter_complaints_table_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table',
            name='amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
