# Generated by Django 3.2.21 on 2024-02-19 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DriveInnapp', '0007_auto_20240219_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_table',
            name='time',
        ),
        migrations.AddField(
            model_name='payment_table',
            name='USER_TABLE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.user_table'),
        ),
    ]
