# Generated by Django 3.2.21 on 2024-02-22 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DriveInnapp', '0008_auto_20240219_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=100)),
                ('IFSC_code', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('LOGIN_TABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DriveInnapp.login_table')),
            ],
        ),
    ]
